"""
HI 741 – Final Project
May 2026
Steven Nichols

analytics.py

Analytics and statistics functions for clinical encounter and patient data.
"""

# Default eligibility criteria used when none are provided
DEFAULT_ELIGIBILITY_CRITERIA: dict = {
    "min_age":       18,
    "max_age":       45,
    "gender":        {"female", "male"},
    "bmi_threshold": 30.0,
    "a1c_threshold": 5.7,
    "smoking":       True,
}


def count_encounters_per_patient(patients: dict) -> dict[str, int]:
    """Return a dict mapping patient_id to number of encounters."""
    return {pid: p.count_encounters() for pid, p in patients.items()}


def encounters_by_department(departments: dict) -> dict[str, int]:
    """Return a dict mapping department name to number of encounters."""
    return {dept.name: dept.encounter_count() for dept in departments.values()}


def identify_eligible_patients(patients: dict, criteria: dict = None) -> list[str]:
    """Return a sorted list of patient_ids for patients who meet all criteria."""
    if criteria is None:
        criteria = DEFAULT_ELIGIBILITY_CRITERIA
    return sorted(pid for pid, p in patients.items() if p.meets_criteria(criteria))


def monitor_provider_workload(providers: dict, top_n: int | None = None) -> dict[str, int]:
    """Return providers sorted descending by encounter count, optionally capped at top_n."""
    ranked = sorted(providers.values(), key=lambda p: p.encounter_count(), reverse=True)
    if top_n is not None:
        ranked = ranked[:top_n]
    return {p.provider_id: p.encounter_count() for p in ranked}


def department_revenue(departments: dict) -> dict[str, float]:
    """Return total procedure cost generated by each department, keyed by department name."""
    return {dept.name: round(dept.total_revenue(), 2) for dept in departments.values()}


def key_statistics(patients: dict, encounters: dict) -> dict:
    """Compute summary statistics suitable for chart display in the UI."""
    ages  = [p.age for p in patients.values()]
    bmis  = [p.bmi for p in patients.values() if p.bmi is not None]

    genders: dict[str, int] = {}
    for p in patients.values():
        genders[p.gender] = genders.get(p.gender, 0) + 1

    enc_types: dict[str, int] = {}
    for e in encounters.values():
        enc_types[e.encounter_type] = enc_types.get(e.encounter_type, 0) + 1

    return {
        "ages":            ages,
        "bmis":            bmis,
        "genders":         genders,
        "encounter_types": enc_types,
        "patient_count":   len(patients),
        "encounter_count": len(encounters),
    }
